title: Shengjie Liu
description: > # this means to ignore newlines until "baseurl:"
  Sims 2020: Hong Kong
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sjliu.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shengjie Liu # add your name
author-img: sj.jpg # add your photo
about-author: "I am a research assistant at the <a href='https://www.hku.hk'>University of Hong Kong</a>. 
My research focuses on using machine/deep learning to interpret satellite images and extract useful information.
Some of the applications are land use classification, local climate zone mapping and PM2.5 estimation.
The techniques used include active learning, multitask learning and multisource data fusion. 
Recent research interests are deep few-shot learning for satellite image classification."
news: ""
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: stop68 # add your Github handle
social-linkedin: shengjie-liu-2696a1b2 # add your Linkedin handle
social-email: sjliu.me@gmail.com # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-maps

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
