title: Hello, world! I'm Shengjie Liu.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shengjie.xyz" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shengjie Liu # add your name
author-img: sj.jpg # add your photo
about-author: "<p><strong>I am looking for a PhD position in Fall 2020.</strong></p>
I received my BSc degree from <a href='http://sysu.edu.cn/2012/en/index.htm'>Sun Yat-sen U</a> in June 2019. 
During my four-year undergraduate study, I have developed an interest in remote sensing and machine learning. 
Specifically, I use state-of-the-art techniques and satellite data to monitor the Earth environment. 
My thesis was about using deep learning to generate precise and beautiful maps with multisource satellite data under the condition of very few samples. My advisors were <a href='https://scholar.google.com/citations?hl=zh-CN&user=tUe4JDoAAAAJ'>Dr. Qian Shi</a> and <a href='https://scholar.google.com/citations?user=GBTF4cgAAAAJ&hl=zh-CN&oi=ao'>Dr.Zhixin Qi</a>. "
news: ""
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: stop68 # add your Github handle
social-linkedin: shengjie-liu-2696a1b2 # add your Linkedin handle
social-email: liushengjie0756@gmail.com # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-maps

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
